---
# Start Splunk Universal Forwarder (Windows)

- name: Start Splunk Universal Forwarder service
  win_service:
    name: SplunkForwarder
    state: started

- name: Display Splunk Universal Forwarder status
  debug:
    msg: "Splunk Universal Forwarder is running on {{ ansible_hostname }} and forwarding to {{ splunk_hf_ip }}:9997"
